* bufferpool

Different implementations of bufferpool.

Designed around prior experiences with "larger than memory" problems. Data analysis, append-only databases, etc. 
All things I've done professionally or personally.

If you happen upon this project and think that, yes, you'd like to help, or if you want to use it, I welcome help 
(but I'll be quite stubborn about the license). 

* implementation languages.

** Python

This is the prototype, used for testing ideas and experiementing. Effectively the standard.

*** notes

The Python library is intentionally "pure" stdlib Python, not using any third party packages.  This 
simplifies testing, deployments, etc.

** Go

This will be used in my own projects. 

** plans

Common Lisp, Rust

- CL - for sophistictated projects

- Rust - for really going for performance and learning about the borrow checker.



* license

  (C) Affero GPL v 3.0 - https://www.gnu.org/licenses/agpl-3.0.en.html

  This means, in short, you can not use this software at all - either
  in packaged software or as a SaaS service without releasing your
  modifications.

  Contact me if you want to use it commercially.

  paul@nathan.house


* references
https://15445.courses.cs.cmu.edu/fall2020/notes/05-bufferpool.pdf
