* bufferpool

Different implementations of bufferpool.

Designed around prior experiences with "larger than memory" problems. Data analysis, append-only databases, etc.
All things I've done professionally or personally.

If you happen upon this project and think that, yes, you'd like to help, or if you want to use it, I welcome help
(but I'll be quite stubborn about the license).

* implementation languages.

** Python

This is a prototype, used for testing ideas and experiementing.

*** notes

The Python library is intentionally "pure" stdlib Python, not using any third party packages.  This
simplifies testing, deployments, etc.

** Go

Go: half done.

** Rust

In progress. Will be a multi-threaded reference implementation.



* license

  (C) Affero GPL v 3.0 - https://www.gnu.org/licenses/agpl-3.0.en.html

  This means, in short, you MUST use share all source code this is linked or associated with. 

  Contact me if you want to use it commercially.

  paul@nathan.house


* references
https://15445.courses.cs.cmu.edu/fall2020/notes/05-bufferpool.pdf
